### ISSUE TITLE
Debian Stretch Image Not Responding on Start up

### ISSUE THREAD

**Issue by amanharitsh123** [sugarlabs/rpi23-gen-image#15] opened 2018-02-07 13:13 UTC
I built the Debian stretch sugar image using the script and then flashed it onto my SD card(Class 10)
using bmaptool.
First Boot: All I can see was the XO icon (Choose color). Keyboard and mouse were not working, I tried plugging them again, still no response. 
Second Boot: Debian Login prompt with the freezed cursor, again mouse and keyboard were not working.

P.S: I am using RPi 3 and its working fine with Raspbian OS.

**Comment by quozl** [comment] 2018-02-07 18:57
Debian archive changes over time as packages are uploaded, so it is common for rpi23-gen-image to fail.

Our Sugar Labs fork of rpi23-gen-image has not been maintained since August when we merged the GSoC work by @Rishabh42.  I'm not interested in maintaining it alone, and nor is anybody else.

Upstream is https://github.com/drtyhlpr/rpi23-gen-image and has at least 18 commits after August, and likely another set of commits not in this fork.

Please reproduce your problem with the upstream repository first, and if the problem occurs with that raise your issue in that repository.

Otherwise, please merge this repository with the later upstream commits to fix your problem, and take on maintenance responsibility.

You've mentioned in IRC your need is for a Sugarizer school box project this year.  I don't think this needs the Sugar desktop does it?

**Comment by Rishabh42** [comment] 2018-02-07 20:43
Thanks for mentioning the issue Aman, I will try to rectify this as soon as
possible.

And James sir, I would like to maintain thIs repository and would be
grateful if you could also help.

Warm regards
Rishabh

**Comment by amanharitsh123** [comment] 2018-02-08 04:56
@Rishabh42 I would love to assist you in maintaining this repository.

**Comment by amanharitsh123** [comment] 2018-02-08 05:05
@quozl  In sugarizer school box project,  it is mentioned that a client interface should appear on the Rpi as well, I was thinking that it would be better to use sugar desktop's Browser activity for that because  I supposed that the teachers would be more familiar with sugar rather than raspbian.

Sir, Is it advisable to build an image with the default raspbian and use the client in chromium?

**Comment by quozl** [comment] 2018-02-08 05:36
This is not for me to say.  Speak with the leading mentors of the Sugarizer school box project.  What has been said so far on https://wiki.sugarlabs.org/go/Summer_of_Code/2018 is that the Sugarizer client would be used, not the Sugar desktop, so nothing in this repository would be used.  I agree with that; since Sugar desktop and Sugarizer behave differently, it would be confusing to present Sugar desktop to a group of users trying to deploy Sugarizer.

**Closed as completed** 2018-02-08 08:12 UTC
